In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('new/full.csv')
df

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,propertyCode,thumbnail,externalReference,numPhotos,floor,price,...,has3DTour,has360,hasStaging,highlight,superTopHighlight,topNewDevelopment,index,neighborhood,labels,newDevelopmentFinished
0,0,0.0,0.0,0,100610812,https://img3.idealista.com/blur/WEB_LISTING/0/...,5644,48,bj,335000.0,...,False,False,True,{'groupDescription': 'Destacado'},False,False,NaN,NaN,NaN,NaN
1,1,1.0,1.0,1,101766825,https://img3.idealista.com/blur/WEB_LISTING/0/...,ACP1219A,57,2,1650000.0,...,False,True,True,{'groupDescription': 'Destacado'},False,False,NaN,NaN,NaN,NaN
2,2,2.0,2.0,2,98058039,https://img3.idealista.com/blur/WEB_LISTING/0/...,W-02OZM3,26,NaN,770000.0,...,False,False,False,{'groupDescription': 'Destacado'},False,False,NaN,NaN,NaN,NaN
3,3,3.0,3.0,3,102450094,https://img3.idealista.com/blur/WEB_LISTING/0/...,nm00895,36,1,175000.0,...,False,False,False,{'groupDescription': 'Destacado'},False,False,NaN,NaN,NaN,NaN
4,4,4.0,4.0,4,100528636,https://img3.idealista.com/blur/WEB_LISTING/0/...,3385-04514,46,2,280000.0,...,False,False,False,{'groupDescription': 'Destacado'},False,False,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6510,195,NaN,NaN,195,101494299,https://img3.idealista.com/blur/WEB_LISTING/0/...,W-02SDQA,27,1,2500000.0,...,False,False,False,NaN,False,False,20.0,Castellana,"[{'name': 'luxuryType', 'text': 'Lujo'}]",NaN
6511,196,NaN,NaN,196,102878198,https://img3.idealista.com/blur/WEB_LISTING/0/...,NaN,22,bj,79000.0,...,False,False,False,NaN,False,False,21.0,Ensanche de Vallecas - La Gavia,NaN,NaN
6512,197,NaN,NaN,197,97684223,https://img3.idealista.com/blur/WEB_LISTING/0/...,73056985,13,NaN,126800.0,...,False,False,False,NaN,False,False,22.0,NaN,NaN,NaN
6513,198,NaN,NaN,198,102620357,https://img3.idealista.com/blur/WEB_LISTING/0/...,MAYOR,14,NaN,126100.0,...,False,False,False,NaN,False,False,23.0,NaN,NaN,NaN
6514,199,NaN,NaN,199,100726970,https://img3.idealista.com/blur/WEB_LISTING/0/...,MAYOR,14,NaN,126100.0,...,False,False,False,NaN,False,False,24.0,NaN,NaN,NaN

In [3]:
df.columns

Index(['Unnamed: 0.3', 'Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0',
       'propertyCode', 'thumbnail', 'externalReference', 'numPhotos', 'floor',
       'price', 'propertyType', 'operation', 'size', 'exterior', 'rooms',
       'bathrooms', 'address', 'province', 'municipality', 'district',
       'country', 'latitude', 'longitude', 'showAddress', 'url', 'distance',
       'description', 'hasVideo', 'status', 'newDevelopment', 'hasLift',
       'parkingSpace', 'priceByArea', 'detailedType', 'suggestedTexts',
       'hasPlan', 'has3DTour', 'has360', 'hasStaging', 'highlight',
       'superTopHighlight', 'topNewDevelopment', 'index', 'neighborhood',
       'labels', 'newDevelopmentFinished'],
      dtype='object')

In [4]:
df = df[['price', 'propertyType', 'size', 'exterior', 'rooms',
         'bathrooms', 'address', 'province', 'municipality',
         'latitude', 'longitude', 'status', 'newDevelopment', 'hasLift',
         'parkingSpace', 'priceByArea', 'detailedType', 'highlight']]

# Missing Values

In [118]:
df.isnull().sum()

price                0
propertyType         0
size                 0
exterior          1948
rooms                0
bathrooms            0
address              0
province             0
municipality         0
latitude             0
longitude            0
status               0
newDevelopment       0
hasLift           1777
parkingSpace      3992
priceByArea          0
detailedType         0
highlight         3980
dtype: int64

In [5]:
# Exterior cleaned
df['exterior'] = df['exterior'].fillna(False)

/var/folders/vs/d74l8bqd271fb7t3zg22mgs40000gn/T/ipykernel_80869/1317668624.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['exterior'] = df['exterior'].fillna(False)

In [6]:
# hasLift cleaned
df['hasLift'] = df['hasLift'].fillna(False)

/var/folders/vs/d74l8bqd271fb7t3zg22mgs40000gn/T/ipykernel_80869/538161793.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hasLift'] = df['hasLift'].fillna(False)

In [7]:
# highlight cleaned
df['highlight'] = df['highlight'].fillna("{'groupDescription': None}")

/var/folders/vs/d74l8bqd271fb7t3zg22mgs40000gn/T/ipykernel_80869/4113140830.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['highlight'] = df['highlight'].fillna("{'groupDescription': None}")

In [122]:
# parkingSpace cleaned
df['parkingSpace'] = df['parkingSpace'].fillna("{'hasParkingSpace': False, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': None}")

/var/folders/xs/s4fj4wdx6f7fkjpgcmjzz2lc0000gn/T/ipykernel_30069/1879921617.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['parkingSpace'] = df['parkingSpace'].fillna("{'hasParkingSpace': False, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': None}")

In [123]:
df.isnull().sum()

price             0
propertyType      0
size              0
exterior          0
rooms             0
bathrooms         0
address           0
province          0
municipality      0
latitude          0
longitude         0
status            0
newDevelopment    0
hasLift           0
parkingSpace      0
priceByArea       0
detailedType      0
highlight         0
dtype: int64

# Feature Engineering
* parkingSpace included needs to be fixed
* parkingSpace needs to be expanded
* highlight needs to be expanded
* detailedType needs to be expanded

In [124]:
# parkingSpace included fixed
df['parkingSpace'] = df['parkingSpace'].apply(lambda x: "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': True, 'parkingSpacePrice': None}" if x == "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': True}" else x)

/var/folders/xs/s4fj4wdx6f7fkjpgcmjzz2lc0000gn/T/ipykernel_30069/1422656108.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['parkingSpace'] = df['parkingSpace'].apply(lambda x: "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': True, 'parkingSpacePrice': None}" if x == "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': True}" else x)

In [125]:
# unique parkingSpaces are now consistent
df['parkingSpace'].unique()

array(["{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': True, 'parkingSpacePrice': None}",
       "{'hasParkingSpace': False, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': None}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 25000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 20000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 2000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 90000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 7500.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 60000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 5000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 37000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 17850.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 80000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 30000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 29000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 10000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 65000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 95000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 21000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 50000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 7000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 75.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 16000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 19000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 1.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 40000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 20.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 12000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 80.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 14000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 23000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 55000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 38000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 28000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 85000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 7250.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 29800.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 24000.0}",
       "{'hasParkingSpace': True, 'isParkingSpaceIncludedInPrice': False, 'parkingSpacePrice': 15000.0}"],
      dtype=object)

In [126]:
df['detailedType'].unique()

array(["{'typology': 'flat'}",
       "{'typology': 'flat', 'subTypology': 'duplex'}",
       "{'typology': 'flat', 'subTypology': 'penthouse'}",
       "{'typology': 'chalet'}",
       "{'typology': 'chalet', 'subTypology': 'terracedHouse'}",
       "{'typology': 'chalet', 'subTypology': 'independantHouse'}",
       "{'typology': 'chalet', 'subTypology': 'semidetachedHouse'}",
       "{'typology': 'countryHouse', 'subTypology': 'countryHouse'}",
       "{'typology': 'countryHouse', 'subTypology': 'casaDePueblo'}",
       "{'typology': 'flat', 'subTypology': 'studio'}",
       "{'typology': 'countryHouse', 'subTypology': 'caseron'}",
       "{'typology': 'countryHouse', 'subTypology': 'casale'}"],
      dtype=object)

In [8]:
# fixing detailedType
df['detailedType'] = df['detailedType'].apply(lambda x: "{'typology': 'flat', 'subTypology': 'standardFlat'}" if x == "{'typology': 'flat'}" else x)
df['detailedType'] = df['detailedType'].apply(lambda x: "{'typology': 'chalet', 'subTypology': 'standardChalet'}" if x == "{'typology': 'chalet'}" else x)

/var/folders/vs/d74l8bqd271fb7t3zg22mgs40000gn/T/ipykernel_80869/1080788751.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['detailedType'] = df['detailedType'].apply(lambda x: "{'typology': 'flat', 'subTypology': 'standardFlat'}" if x == "{'typology': 'flat'}" else x)
/var/folders/vs/d74l8bqd271fb7t3zg22mgs40000gn/T/ipykernel_80869/1080788751.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['detailedType'] = df['detailedType'].apply(lambda x: "{'typology': 'chalet', 'subTypology': 'standardChalet'}" if x == "{'typology': 'chalet'}" else x)

In [9]:
# detailedTypes are now consistent
df['detailedType'].unique()

array(["{'typology': 'flat', 'subTypology': 'standardFlat'}",
       "{'typology': 'flat', 'subTypology': 'duplex'}",
       "{'typology': 'flat', 'subTypology': 'penthouse'}",
       "{'typology': 'chalet', 'subTypology': 'standardChalet'}",
       "{'typology': 'chalet', 'subTypology': 'terracedHouse'}",
       "{'typology': 'chalet', 'subTypology': 'independantHouse'}",
       "{'typology': 'chalet', 'subTypology': 'semidetachedHouse'}",
       "{'typology': 'countryHouse', 'subTypology': 'countryHouse'}",
       "{'typology': 'countryHouse', 'subTypology': 'casaDePueblo'}",
       "{'typology': 'flat', 'subTypology': 'studio'}",
       "{'typology': 'countryHouse', 'subTypology': 'caseron'}",
       "{'typology': 'countryHouse', 'subTypology': 'casale'}"],
      dtype=object)

In [12]:
# Converting string of dicts --> dicts

from ast import literal_eval # Library for string evaluation

df['parkingSpace'] = df['parkingSpace'].apply(literal_eval)
df['highlight'] = df['highlight'].apply(literal_eval)
df['detailedType'] = df['detailedType'].apply(literal_eval)

ValueError: malformed node or string: nan

In [13]:
df = pd.concat([df,
           pd.json_normalize(df['parkingSpace']),
           pd.json_normalize(df['highlight']),
           pd.json_normalize(df['detailedType'])],
          axis = 1)

In [14]:
del df['parkingSpace']
del df['highlight']
del df['detailedType']

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6515 entries, 0 to 6514
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   price                          6515 non-null   float64
 1   propertyType                   6515 non-null   object
 2   size                           6515 non-null   float64
 3   exterior                       6515 non-null   bool
 4   rooms                          6515 non-null   int64
 5   bathrooms                      6515 non-null   int64
 6   address                        6515 non-null   object
 7   province                       6515 non-null   object
 8   municipality                   6515 non-null   object
 9   latitude                       6515 non-null   float64
 10  longitude                      6515 non-null   float64
 11  status                         6515 non-null   object
 12  newDevelopment                 6515 non-null   bool
 13  hasLift                        6515 non-null   bool
 14  priceByArea                    6515 non-null   float64
 15  hasParkingSpace                6515 non-null   bool
 16  isParkingSpaceIncludedInPrice  6515 non-null   bool
 17  parkingSpacePrice              198 non-null    float64
 18  groupDescription               2535 non-null   object
 19  typology                       6515 non-null   object
 20  subTypology                    6515 non-null   object
dtypes: bool(5), float64(6), int64(2), object(8)
memory usage: 846.3+ KB

In [15]:
df

,price,propertyType,size,exterior,rooms,bathrooms,address,province,municipality,latitude,longitude,status,newDevelopment,hasLift,priceByArea
0,335000.0,flat,136.0,True,3,2,SIGRID,Madrid,Rivas-Vaciamadrid,40.352160,-3.518342,good,False,True,2463.0
1,1650000.0,flat,179.0,True,2,3,Calle del Príncipe de Vergara,Madrid,Madrid,40.433593,-3.677788,good,False,True,9218.0
2,770000.0,flat,109.0,True,2,2,barrio Ibiza,Madrid,Madrid,40.416551,-3.672922,good,False,True,7064.0
3,175000.0,flat,49.0,True,1,1,"Calle de los Morales, 10",Madrid,Madrid,40.361994,-3.756360,good,False,True,3571.0
4,280000.0,flat,121.0,True,4,2,Calle del Río Ulla,Madrid,Madrid,40.432982,-3.643371,good,False,False,2314.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6510,2500000.0,flat,341.0,True,4,2,barrio Castellana,Madrid,Madrid,40.433505,-3.681772,good,False,True,7331.0
6511,79000.0,flat,66.0,True,1,1,Calle de José Gutiérrez Maroto,Madrid,Madrid,40.362047,-3.606132,good,False,True,1197.0
6512,126800.0,chalet,159.0,False,3,3,Calle del Pintor Álvaro Delgado,Madrid,Olmeda de las Fuentes,40.369379,-3.218587,good,False,False,797.0
6513,126100.0,chalet,150.0,False,3,2,MAYOR,Madrid,Olmeda de las Fuentes,40.371338,-3.221649,good,False,False,841.0
6514,126100.0,chalet,150.0,False,3,3,MAYOR,Madrid,Olmeda de las Fuentes,40.370631,-3.221711,good,False,False,841.0

In [137]:
df.to_csv('cleaned_df.csv')