In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('new/full.csv')

In [9]:
df.columns

Index(['Unnamed: 0.3', 'Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0',
       'propertyCode', 'thumbnail', 'externalReference', 'numPhotos', 'floor',
       'price', 'propertyType', 'operation', 'size', 'exterior', 'rooms',
       'bathrooms', 'address', 'province', 'municipality', 'district',
       'country', 'latitude', 'longitude', 'showAddress', 'url', 'distance',
       'description', 'hasVideo', 'status', 'newDevelopment', 'hasLift',
       'parkingSpace', 'priceByArea', 'detailedType', 'suggestedTexts',
       'hasPlan', 'has3DTour', 'has360', 'hasStaging', 'highlight',
       'superTopHighlight', 'topNewDevelopment', 'index', 'neighborhood',
       'labels', 'newDevelopmentFinished'],
      dtype='object')

In [23]:
df = df[[
       'numPhotos',
       'price', 'propertyType', 'size', 'exterior', 'rooms',
       'bathrooms', 'address', 'province', 'municipality', 'latitude', 'longitude', 
       'status', 'newDevelopment', 'hasLift',
       'parkingSpace', 'priceByArea', 'detailedType', 'suggestedTexts',
       'hasStaging', 'highlight',
       'neighborhood']]

In [17]:
df

,numPhotos,floor,price,propertyType,size,exterior,rooms,bathrooms,address,province,...,status,newDevelopment,hasLift,parkingSpace,priceByArea,detailedType,suggestedTexts,hasStaging,highlight,neighborhood
0,48,bj,335000.0,flat,136.0,True,3,2,SIGRID,Madrid,...,good,False,True,"{'hasParkingSpace': True, 'isParkingSpaceInclu...",2463.0,{'typology': 'flat'},"{'subtitle': 'Rivas Centro, Rivas-Vaciamadrid'...",True,{'groupDescription': 'Destacado'},NaN
1,57,2,1650000.0,flat,179.0,True,2,3,Calle del Príncipe de Vergara,Madrid,...,good,False,True,"{'hasParkingSpace': True, 'isParkingSpaceInclu...",9218.0,{'typology': 'flat'},"{'subtitle': 'Lista, Madrid', 'title': 'Piso e...",True,{'groupDescription': 'Destacado'},NaN
2,26,NaN,770000.0,flat,109.0,True,2,2,barrio Ibiza,Madrid,...,good,False,True,NaN,7064.0,{'typology': 'flat'},"{'subtitle': 'Ibiza, Madrid', 'title': 'Piso'}",False,{'groupDescription': 'Destacado'},NaN
3,36,1,175000.0,flat,49.0,True,1,1,"Calle de los Morales, 10",Madrid,...,good,False,True,"{'hasParkingSpace': True, 'isParkingSpaceInclu...",3571.0,{'typology': 'flat'},"{'subtitle': 'Pau de Carabanchel, Madrid', 'ti...",False,{'groupDescription': 'Destacado'},NaN
4,46,2,280000.0,flat,121.0,True,4,2,Calle del Río Ulla,Madrid,...,good,False,False,NaN,2314.0,{'typology': 'flat'},"{'subtitle': 'Pueblo Nuevo, Madrid', 'title': ...",False,{'groupDescription': 'Destacado'},NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6510,27,1,2500000.0,flat,341.0,True,4,2,barrio Castellana,Madrid,...,good,False,True,NaN,7331.0,{'typology': 'flat'},"{'subtitle': 'Castellana, Madrid', 'title': 'P...",False,NaN,Castellana
6511,22,bj,79000.0,flat,66.0,True,1,1,Calle de José Gutiérrez Maroto,Madrid,...,good,False,True,"{'hasParkingSpace': True, 'isParkingSpaceInclu...",1197.0,{'typology': 'flat'},"{'subtitle': 'Ensanche de Vallecas - La Gavia,...",False,NaN,Ensanche de Vallecas - La Gavia
6512,13,NaN,126800.0,chalet,159.0,NaN,3,3,Calle del Pintor Álvaro Delgado,Madrid,...,good,False,NaN,"{'hasParkingSpace': True, 'isParkingSpaceInclu...",797.0,"{'typology': 'chalet', 'subTypology': 'terrace...","{'subtitle': 'Olmeda de las Fuentes', 'title':...",False,NaN,NaN
6513,14,NaN,126100.0,chalet,150.0,NaN,3,2,MAYOR,Madrid,...,good,False,NaN,NaN,841.0,"{'typology': 'chalet', 'subTypology': 'terrace...","{'subtitle': 'Olmeda de las Fuentes', 'title':...",False,NaN,NaN
6514,14,NaN,126100.0,chalet,150.0,NaN,3,3,MAYOR,Madrid,...,good,False,NaN,NaN,841.0,"{'typology': 'chalet', 'subTypology': 'terrace...","{'subtitle': 'Olmeda de las Fuentes', 'title':...",False,NaN,NaN

In [19]:
### Missing Values

In [24]:
df.isnull().sum()

numPhotos            0
price                0
propertyType         0
size                 0
exterior             0
rooms                0
bathrooms            0
address              0
province             0
municipality         0
latitude             0
longitude            0
status               0
newDevelopment       0
hasLift           1777
parkingSpace      3992
priceByArea          0
detailedType         0
suggestedTexts       0
hasStaging           0
highlight         3980
neighborhood      3396
dtype: int64

In [22]:
df['exterior'] = df['exterior'].fillna(False)

/var/folders/71/6kdsbn2j2klcyp_x6_w6l51h0000gn/T/ipykernel_70654/92333966.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['exterior'] = df ['exterior'].fillna(False)

In [29]:
df['hasLift'] = df['hasLift'].fillna(False)